{
 "title": "My Apache Spark Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Application status (last run)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "mysparkappprefix.custom_metrics",
     "query": "SELECT time, executor_id as status FROM (SELECT time, last(\"value\"), executor_id FROM \"mysparkappprefix.custom_metrics\" WHERE (\"application\" = 'SparkIngestionTest' AND \"name\" = 'ApplicationStatus'))",
     "select": [
      [
       { "params": [ "executor_id" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "SparkIngestionTest" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "ApplicationStatus" }
     ]
    }
   ]
  },
  {
   "title": "App elapsed time [s] (last run)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "mysparkappprefix.custom_metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "applicationElapsedTimeInSecs" }
     ]
    }
   ]
  },
  {
   "title": "Failed tasks count (last run)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "mysparkappprefix.custom_metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "SparkIngestionTest" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "TaskExMsg" }
     ]
    }
   ]
  },
  {
   "title": "Records processed count (last run)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "mysparkappprefix.custom_metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "recordsCount" }
     ]
    }
   ]
  },
  {
   "title": "Application run status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_executor_id]]",
     "groupBy": [
      { "params": [ "executor_id" ], "type": "tag" }
     ],
     "measurement": "mysparkappprefix.custom_metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "SparkIngestionTest" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "ApplicationStatus" }
     ]
    }
   ]
  },
  {
   "title": "Task processing exception",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_executor_id]]",
     "groupBy": [
      { "params": [ "executor_id" ], "type": "tag" }
     ],
     "measurement": "mysparkappprefix.custom_metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "SparkIngestionTest" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "TaskExMsg" }
     ]
    }
   ]
  },
  {
   "title": "Application elapsed time [s]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mysparkappprefix.custom_metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "SparkIngestionTest" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "applicationElapsedTimeInSecs" }
     ]
    }
   ]
  },
  {
   "title": "Number of processed records",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mysparkappprefix.custom_metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "recordsCount" },
      { "condition": "AND", "key": "application", "operator": "=", "value": "SparkIngestionTest" }
     ]
    }
   ]
  },
  {
   "title": "Task cpu time per node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_executor_id]]",
     "groupBy": [
      { "params": [ "executor_id" ], "type": "tag" }
     ],
     "measurement": "mysparkappprefix.custom_metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "SparkIngestionTest" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Task_executorCpuTime" }
     ]
    }
   ]
  },
  {
   "title": "JVM heap used [MB] per executor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_executor_id]]",
     "groupBy": [
      { "params": [ "executor_id" ], "type": "tag" }
     ],
     "measurement": "jvm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " / 1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "mysparkappprefix" },
      { "condition": "AND", "key": "mem_type", "operator": "=", "value": "heap" },
      { "condition": "AND", "key": "qty", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Tasks kbytes read and written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Task_input_bytesRead",
     "measurement": "mysparkappprefix.custom_metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "SparkIngestionTest" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Task_input_bytesRead" }
     ]
    },
    {
     "alias": "Task_output_bytesWitten",
     "measurement": "mysparkappprefix.custom_metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "SparkIngestionTest" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Task_output_bytesWritten" }
     ]
    }
   ]
  },
  {
   "title": "Tasks records read and written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Task_input_recordsRead",
     "measurement": "mysparkappprefix.custom_metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "SparkIngestionTest" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Task_input_recordsRead" }
     ]
    },
    {
     "alias": "Task_output_recordsWritten",
     "measurement": "mysparkappprefix.custom_metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "SparkIngestionTest" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Task_output_recordsWritten" }
     ]
    }
   ]
  }
 ]
}